name: Create release on push to master

on:
  push:
    branches: [ master ]

jobs:
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: lein deps

      - name: Make release
        run: make release

      - uses: actions/upload-artifact@v1
        with:
          name: battle-asserts
          path: release.tar.gz
